apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-hello-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: python-flask-hello
  template:
    metadata: # metadata
      labels:
        app: python-flask-hello
    spec:
      containers:
        - name: python-flask-hello-container
          image: mrbarker/python-flask-hello
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: python-flask-hello-service
  # namespace: jenkins-namespace
spec:
  selector:
    app: python-flask-hello
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
