apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-pass
type: Opaque
data:
  db-password: YWRtaW4=  # This is the base64 encoded value of 'admin'
  # db-password: S0J0ekdwbk5qdA== #copied from the secret of mysql bitnami